---
abstract: 'Designate resources at PrePAN related to a'
author:
  - 'Kentaro Kuribayashi <kentarok@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install-PrePAN
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.8.1
resources:
  X_prepan:
    author_url: http://prepan.org/user/3XR97nG2Gi
    module_url: http://prepan.org/module/3Yz7PYrBJG
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kentaro/Module-Install-PrePAN.git
version: 0.03
